# Generated by Django 3.1.6 on 2021-02-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0008_auto_20210206_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.URLField(),
        ),
    ]
